server:
  port: 8083
  servlet:
    context-path: /auth-api

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
#    username: root
#    password: 12345678
    
    url: jdbc:mysql://localhost:3309/demodb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:postgresql://192.168.0.221:5432/authdb?createDatabaseIfNotExist=true
#    username: authdb
#    password: authdb#
#    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  application:
    name: auth-server
    
    
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
      
logging:
  file: G:/Micro service/student helper/ssm/log/auth.log
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: ERROR
    org.springframework: INFO
    
    
    
